from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any


OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses"
DEFAULT_MODEL = "gpt-4.1-mini"

_PLAN_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "op": {"type": "string"},
        "args": {"type": "object"},
        "save_as": {"type": "string"},
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "op": {"type": "string"},
                    "args": {"type": "object"},
                    "save_as": {"type": "string"},
                },
                "required": ["op", "args"],
                "additionalProperties": False,
            },
        },
    },
    "additionalProperties": False,
}


class LLMNotConfiguredError(RuntimeError):
    """Raised when the optional LLM backend is missing required config."""


class LLMAPIError(RuntimeError):
    """Raised when the remote LLM endpoint rejects or fails a request."""


def call_llm(prompt: str, user_request: str, config: dict) -> str:
    """
    Call OpenAI and ask it to return one JSON tool plan.

    Input:
        prompt:
            System/planner instruction text, usually loaded from agent/prompt.txt.
        user_request:
            One natural-language request from stdin.
        config:
            Runtime config. This function accepts either a structured dict like
            {"provider": "openai", "openai": {"api_key": "...", "model": "..."}}
            or the Day1 loader shape {"raw": "...yaml text..."}.

    Output:
        A JSON string generated by the model. The caller should parse it with
        json.loads() and validate that the op exists in docs/tool_spec.md.
    """
    settings = _normalize_config(config)
    provider = settings.get("provider", "openai")
    if provider != "openai":
        raise LLMNotConfiguredError(f"Unsupported LLM provider for Day2 agent: {provider!r}")

    api_key = settings.get("api_key") or os.environ.get("OPENAI_API_KEY")
    if not api_key or api_key.startswith("<"):
        raise LLMNotConfiguredError(
            "OpenAI API key is missing. Put it in local config.yaml or set OPENAI_API_KEY."
        )

    model = settings.get("model") or DEFAULT_MODEL
    temperature = _as_float(settings.get("temperature"), default=0.2)
    max_output_tokens = _as_int(settings.get("max_output_tokens"), default=4096)

    payload = {
        "model": model,
        "input": [
            {
                "role": "system",
                "content": prompt,
            },
            {
                "role": "user",
                "content": user_request,
            },
        ],
        "temperature": temperature,
        "max_output_tokens": max_output_tokens,
        "text": {
            "format": {
                "type": "json_schema",
                "name": "eda_tool_plan",
                "schema": _PLAN_SCHEMA,
                "strict": False,
            }
        },
    }

    request = urllib.request.Request(
        OPENAI_RESPONSES_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            response_data = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        message = exc.read().decode("utf-8", errors="replace")
        raise LLMAPIError(f"OpenAI API request failed with HTTP {exc.code}: {message}") from exc
    except urllib.error.URLError as exc:
        raise LLMAPIError(f"OpenAI API request failed: {exc.reason}") from exc

    output_text = _extract_output_text(response_data)
    if not output_text:
        raise LLMAPIError("OpenAI API returned no output text.")
    return output_text


def _normalize_config(config: dict) -> dict[str, Any]:
    if not isinstance(config, dict):
        return {}
    if "raw" in config:
        return _parse_simple_yaml_config(str(config.get("raw", "")))

    openai_config = config.get("openai", {}) or {}
    generation_config = config.get("generation", {}) or {}
    return {
        "provider": config.get("provider", "openai"),
        "api_key": openai_config.get("api_key"),
        "model": openai_config.get("model"),
        "temperature": generation_config.get("temperature"),
        "max_output_tokens": generation_config.get("max_output_tokens"),
    }


def _parse_simple_yaml_config(raw: str) -> dict[str, Any]:
    """
    Parse the small config.example.yaml shape without adding a PyYAML dependency.
    """
    result: dict[str, Any] = {}
    section: str | None = None

    for raw_line in raw.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.endswith(":"):
            section = line[:-1].strip()
            continue
        if ":" not in line:
            continue

        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip().strip("'\"")

        if section is None:
            result[key] = value
        else:
            result[f"{section}.{key}"] = value

    return {
        "provider": result.get("provider", "openai"),
        "api_key": result.get("openai.api_key"),
        "model": result.get("openai.model"),
        "temperature": result.get("generation.temperature"),
        "max_output_tokens": result.get("generation.max_output_tokens"),
    }


def _extract_output_text(response_data: dict[str, Any]) -> str:
    if isinstance(response_data.get("output_text"), str):
        return response_data["output_text"]

    chunks: list[str] = []
    for item in response_data.get("output", []):
        for content in item.get("content", []):
            text = content.get("text")
            if isinstance(text, str):
                chunks.append(text)
    return "".join(chunks).strip()


def _as_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _as_int(value: Any, default: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default
